spring.application.name=Excel_Crud_App
server.port=9090

spring.thymeleaf.cache=false
spring.messages.encoding=UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true
